### ISSUE TITLE
Should an extension change the descriptions of another's fields?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/ocds_budget_and_spend_extension#2]
This extension changes the descriptions of several fields in `BudgetBreakdown` from ocds_budget_breakdown_extension. I think we should instead change the descriptions by changing that extension; I think we shouldn't set a precedent of having extensions change others' field descriptions, which challenges consistent semantics.

**Comment by timgdavies** [comment]
Good thought and spot.

In fact, I think we can resolve this particular case by removing those changes - as they were left-over from when I thought I would re-use `budgetBreakdown` for the `financialProgress/breakdown` (and so would need it to refer to both budget and spend), whereas I have created a separate new object for this. 

However, on the more general point of precent (possibly may want to move this thread elsewhere?): if we were needing to tweak definitions from another extension, but could only do that by creating a version of that extension, that would mean that we would need to declare that this extension depends though on use of a particular version of the other extension - which I don't know if we support yet - and which potentially adds another layer of adoption complexity. 

Would the alternative be to think about our review process for extensions such that we can:

* View each original and changed description side-by-side;
* Make a judgement call on whether the changes are descriptive or semantic;
* Make a judgement call on whether those changes would reasonably cause problems for users of the data;

Particularly given we're not making the same kinds of commitments, or placing the same kinds of requirements, on/for extensions are we are for the core standard.

**Comment by jpmckinney** [comment]
The `dependencies` field in `extension.json` is a URL to an extension, which can reference a specific version (or simply the `master` branch).

I'm going to assume the changes would be descriptive, not semantic, as semantic changes to an extension (nevermind semantic changes by another extension) need to be done carefully and involve a set of concerns that would be long to address.

So for descriptive changes, I think it's better to either update the other extension, or describe the use of the other's fields in the prose documentation. As an example of the former, I believe we've sometimes updated descriptions of core fields based on their use by extensions, though I can't find a quick example. As an example of the latter, the [Budget and projects](https://github.com/open-contracting/ocds_budget_projects_extension#guidance) extension provides additional guidance for core fields. The same approaches can be taken between extensions.

We can move/document this elsewhere if the conversation becomes long.
